Task/remove ac tool
valtech/aem-advanced-permissions-manager pull request #12
Opened 2022-09-05 07:37 UTC by vivekmalviya0104

1. Refactoring the code 
2. Using now repoinit script to create users and groups
3. Adding rep:policy nodes, containing restrictions for dam path as content package
4. Changed the app path from /apps/valtech/aapm-examples to /apps/aapm-examples, because the repoint cfg.json triggers the slingRepositoryInitializer on 2nd level /apps/aapm-examples/osgiconfig/org.apache.sling.jcr.repoinit.RepositoryInitializer~aapm.cfg.json
5. Changed the ReadMe file

2022-09-09 08:56 UTC, gruberrolandvaltech requested changes

2022-09-09 08:56 UTC, gruberrolandvaltech commented on README.md
> +- /apps/aapm
The tool is in /apps/valtech/aapm(-examples)

2022-09-09 08:56 UTC, gruberrolandvaltech commented on all/pom.xml
> +                            <target>/apps/aapm/install</target>
Please keep /apps/valtech

2022-09-09 08:56 UTC, gruberrolandvaltech commented on all/src/main/content/META-INF/vault/filter.xml
> -    <filter root="/apps/valtech/aapm"/>
Keep the valtech

2022-09-09 08:56 UTC, gruberrolandvaltech commented on README.md
> +- /apps/aapm
Keep valtech

2022-09-09 08:56 UTC, gruberrolandvaltech commented on examples.ui.apps/src/main/content/jcr_root/apps/aapm-examples/pbop/permissions/users/pbop-ace-user.yaml
> +# Deprecated as now using repoinit to create users and groups.
No need for deprecation

2022-09-09 08:56 UTC, gruberrolandvaltech commented on examples.ui.config/src/main/content/META-INF/vault/filter.xml
> +    <filter root="/apps/aapm-examples/osgiconfig"/>
keep valtech

2022-09-09 08:56 UTC, gruberrolandvaltech commented on examples.ui.config/src/main/content/jcr_root/apps/aapm-examples/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config~aapm.cfg.json
> +  "org.apache.sling.commons.log.level": "DEBUG",
No debug logging by default, I think we can remove the whole config. There is no need for an extra log file for most users.

2022-09-09 08:56 UTC, gruberrolandvaltech commented on examples/pom.xml
> +                            <target>/apps/aapm-examples/install</target>
keep valtech

2022-09-09 08:56 UTC, gruberrolandvaltech commented on examples/src/main/content/META-INF/vault/filter.xml
> +    <filter root="/apps/aapm-examples"/>
keep valtech

2022-09-12 07:22 UTC, vivekmalviya0104 commented
Added back the valtech folder

2022-09-30 09:19 UTC, gruberrolandvaltech commented on examples.ui.apps/pom.xml
> +    <!-- D E P E Npob D E N C I E S                                                -->
pob?

2022-10-05 06:47 UTC, gruberrolandvaltech approved these changes

2022-10-05 06:52 UTC, merged